platform :ios, '8.0'

xcodeproj 'SpotzCNCCustomer-Sample-Swift'

#pod 'SpotzCNCCustomerSDK', :path => '../../../spotz-cnc-client-sdk-ios' # internal only
pod 'SpotzCNCCustomerSDK', :git => 'https://github.com/localz/Spotz-CNC-Customer-iOS-SDK.git'
pod 'SpotzSDK', :git=>'https://github.com/localz/Spotz3-iOS-SDK', :branch=>'3.1.0.7_beta'
pod 'SpotzPushSDK', :git =>'https://github.com/localz/Spotz-Push-iOS-SDK'

pod 'MBProgressHUD'

